package main

// DO NOT EDIT, this file is generated by hover at compile-time for the flutter_usb_go plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	flutter_usb_go "github.com/meilab/flutter_usb_go/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&flutter_usb_go.FlutterUsbGoPlugin{}))
}
